---
baseurl:
  description: "Domain URL for swapi.com"
  type: "string"
  secret: false
  required: true
dbuser:
  description: "Username for user database"
  type: "string"
  secret: false
  required: false
dbpass:
  description: "Password for user database"
  type: "string"
  secret: true
  required: false
